language: php

jobs:
  include:
    - php: 5.6
    - php: 5.5
      dist: trusty
    - php: 5.4
      dist: trusty
    - php: 5.3
      dist: precise

notifications:
  email:
    - me@benplummer.co.uk

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

notifications:
    on_success: always
    on_failure: always
